name: carpooling_app
description: Co-voiturage local avec Flutter et Firebase

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.7
  provider: ^6.0.2
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.1
  flutter_local_notifications: ^9.1.4
  sqflite: ^2.0.0+4
  cached_network_image: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true